spring:
  application:
    name: demo
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 300000

  datasource:
    url: jdbc:postgresql://localhost:5432/Transaction
    username: postgres
    password: redhat@2004

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8087

telegram:
  bot:
    token: 8516339362:AAGqawmBgzHcEWfYOmmLgbu5xlCHsJt6D1g
  chat:
    id: 5745827016
