spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/Transaction
    username: user_name
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8087

telegram:
  bot:
    token: {$TelegramToken}
  chat:
    id: "{ChatID}"
